feat: added autoscaling and ml node
jenkins-x-terraform/terraform-jx-azure pull request #18
Opened 2021-06-18 14:49 UTC by tomhobson

2021-06-18 14:54 UTC, hervelemeur commented on terraform-jx-cluster-aks/cluster/variables.tf
> -variable "node_count" {
No `node_count` anymore?

2021-06-18 14:55 UTC, hervelemeur requested changes
Not sure the `node_count` should be removed.

2021-06-18 15:44 UTC, tomhobson commented on terraform-jx-cluster-aks/cluster/variables.tf
> -variable "node_count" {
I just thought the less variables the better to be honest.

Which value do you want to be more important than the other?


If node_count is null then autoscale?
or if max_node_count and min_node_count are null then don't autoscale?

2021-06-18 16:38 UTC, hervelemeur commented on terraform-jx-cluster-aks/cluster/variables.tf
> -variable "node_count" {
For people not wanting autoscale/wanting to keep it simple, `node_count` is all they'll need.

> If node_count is null then autoscale?
or if max_node_count and min_node_count are null then don't autoscale?

Yeah I was thinking something like that :)

2021-06-21 08:11 UTC, tomhobson commented on terraform-jx-cluster-aks/cluster/variables.tf
> -variable "node_count" {
Done :+1:

2021-06-21 08:57 UTC, hervelemeur commented
@tomhobson is it normal that the min and max (ml) nodes counts don't have the same default value in terraform-jx-cluster-aks/variables.tf and in variables.tf?

2021-06-21 09:36 UTC, tomhobson commented
@hervelemeur fixed!

2021-06-21 11:09 UTC, hervelemeur commented
/ok-to-test
/lgtm

2021-06-21 11:10 UTC, merged