fix: bump azurerm provider version to fix issues with casing
jenkins-x-terraform/terraform-jx-azure pull request #26
Opened 2022-03-26 15:56 UTC by ankitm123

Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

This issue was fixed in 2.48.0: https://github.com/hashicorp/terraform-provider-azurerm/pull/10593#issuecomment-781575449

Also these are the allowed values: https://registry.terraform.io/providers/hashicorp/azurerm/2.48.0/docs/resources/key_vault_access_policy#secret_permissions

2022-03-26 16:17 UTC, ankitm123 commented
/cc @tomhobson

2022-03-26 16:18 UTC, ankitm123 commented on terraform-jx-azurekeyvault/main.tf
> +      version = ">=2.48.0"
may be should be restricted to less than version 3, as it may have breaking changes?

2022-03-27 14:49 UTC, tomhobson commented on terraform-jx-azurekeyvault/main.tf
> +      version = ">=2.48.0"
Sounds good to me, let's fix max version.

I think Ted suggested 2.61 was the final working version

2022-03-27 14:49 UTC, tomhobson requested changes
Let's fix max version

2022-03-28 11:48 UTC, ankitm123 commented on terraform-jx-azurekeyvault/main.tf
> +      version = ">=2.48.0"
I think it would be good to test it out with the last 2.X version, for now, let's test with < 3.0

2022-03-28 12:47 UTC, tomhobson commented
/approve

2022-03-28 14:59 UTC, ankitm123 commented
/ok-to-test

2022-03-28 14:59 UTC, ankitm123 commented
oh no untrusted @tomhobson :grimacing:

2022-03-28 15:05 UTC, merged