chore: made dns inline with gcp and aws tfs
jenkins-x-terraform/terraform-jx-azure pull request #4
Opened 2021-04-22 14:41 UTC by tomhobson

I've been trying to bring this inline with: https://github.com/jenkins-x/terraform-google-jx

Before doing some future updates:
* Autoscaling
* Extra domains
* Premium tiers for container registries

2021-04-27 11:06 UTC, jstrachan commented
/ok-to-test

2021-04-27 11:06 UTC, jstrachan commented
/test pr

2021-04-27 12:18 UTC, hervelemeur requested changes

2021-04-27 12:18 UTC, hervelemeur commented on jx-requirements.yml.tpl
> -  %{ endif }
```suggestion
  %{ if domain_enabled }
      dns:
        resourceGroup: ${dns_resource_group}
        tenantId: ${dns_tenant_id}
        subscriptionId: ${dns_subscription_id}
  %{ endif }
```

Not sure but this part seems to be only required when the domain is enabled.

2021-04-27 12:18 UTC, hervelemeur commented on jx-requirements.yml.tpl
>      domain: ${domain_name}
```suggestion
    domain: ${domain}
```

2021-04-27 12:18 UTC, hervelemeur commented on terraform-jx-azuredns/variables.tf
> +  description = "If parent / apex domain is managed in the same "
(I presume it's directly from the google terraform repo which has the same issue)

2021-04-27 12:18 UTC, hervelemeur commented on variables.tf
> -}
```suggestion
variable "dns_enabled" {
  type        = bool
  default     = false
  description = "** Deprecated** Set apex_domain instead"
}
```

2021-04-27 13:34 UTC, tomhobson commented on terraform-jx-azuredns/variables.tf
> +  description = "If parent / apex domain is managed in the same "
Yeah I'll update this in both if you can decide what should be there?

@jstrachan @hervelemeur

2021-04-27 13:38 UTC, tomhobson commented on jx-requirements.yml.tpl
> -  %{ endif }
Looks like this isn't done within the gcp one: https://github.com/jenkins-x/terraform-google-jx/blob/master/modules/jx-requirements-v3.yml.tpl#L10

Can add it but it's up to you

2021-04-27 14:12 UTC, hervelemeur commented on terraform-jx-azuredns/variables.tf
> +  description = "If parent / apex domain is managed in the same "
Good question ^^ I think it should be "namespace" but I'm not sure.

2021-04-27 14:14 UTC, hervelemeur commented on jx-requirements.yml.tpl
> -  %{ endif }
Indeed, there isn't any "dns" entry in GCP jx-requirements.

But as there is one for Azure, I think we should keep it declared only when the domain is enabled. I don't know what would happen if it's declared without any domain enabled.

2021-04-28 11:27 UTC, tomhobson commented on terraform-jx-azuredns/variables.tf
> +  description = "If parent / apex domain is managed in the same "
I've taken the original value, seemed to be a good enough description

2021-04-28 11:34 UTC, hervelemeur commented
/approve

2021-04-28 11:35 UTC, hervelemeur commented
/assign hervelemeur

2021-04-28 11:49 UTC, hervelemeur commented
/lgtm

2021-04-28 11:50 UTC, merged